version: "3.4"
services:
  agentzhao.me:
    container_name: agentzhao.me
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    expose:
      - 8000
    volumes:
      - ./frontend/:/var/www/html/app
    tty: true
